services:
  mongo:
    image: mongo:8.0
    container_name: juicy-forest-db
    ports:
      - "3032:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - juicy-forest-network
    restart: unless-stopped
  
  server:
    build: ./server
    container_name: juicy-forest-server
    ports:
      - "3031:3031"
    environment:
      - PORT=${PORT:-3031}
      - MONGO_URI=mongodb://mongo:27017/juicy-forest
      - JWT_SECRET=${JWT_SECRET:-JWT-SECRET-TOKEN}
    depends_on:
      - mongo
    networks:
      - juicy-forest-network
    restart: unless-stopped
    volumes:
      - ./server:/app
      - /app/node_modules

  gateway:
    build: ./gateway
    container_name: juicy-forest-gateway
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - SERVER_SERVICE_URL=http://server:3031
      - CHAT_SERVICE_URL=http://chat:3033
      - SENSORS_SERVICE_URL=http://sensors:3034
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - server
      - chat
    networks:
      - juicy-forest-network
    restart: unless-stopped
    volumes:
      - ./gateway:/app
      - /app/node_modules
  chat:
    build: ./chat
    container_name: juicy-forest-chat
    ports:
      - "3033:3033"
    environment:
      - PORT=${PORT:-3033}
      - MONGO_URI=mongodb://mongo:27017/juicy-forest
      - JWT_SECRET=${JWT_SECRET:-JWT-SECRET-TOKEN}
    depends_on:
      - mongo 
    networks:
      - juicy-forest-network
    restart: unless-stopped
    volumes:
      - ./chat:/app
      - /app/node_modules

  sensors:
    build: ./sensors
    container_name: juicy-forest-sensors
    ports:
      - "3034:3034"
    environment:
      - PORT=${PORT:-3034}
      - JWT_SECRET=${JWT_SECRET:-JWT-SECRET-TOKEN}
      - MONGO_URI=mongodb://mongo:27017/juicy-forest
      - SERIAL_PORT_PATH=/dev/ttyACM0
    depends_on:
      - mongo 
    networks:
      - juicy-forest-network
    restart: unless-stopped
    volumes:
      - ./sensors:/app
      - /app/node_modules
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"

volumes:
  mongodb_data:
  

networks:
  juicy-forest-network:
    driver: bridge
